[workspace]
members = [
    # Modules
    "./horsejs",
    "./pun",
    "./uuid",

    # Libs
    "./wit-log",
    "./wit-sync-request",
    "./wit-sys",
]

[workspace.dependencies]
wit-bindgen-guest-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "aed92eb" }
wit-log = { path = "./wit-log" }
wit-sys = { path = "./wit-sys" }
wit-sync-request = { path = "./wit-sync-request" }
